### ISSUE TITLE
Installing packages

### ISSUE THREAD

**Issue by lrkrol** [michal-h21/make4ht-action#4]
Thanks for this useful action. Is there a way to have it auto-install missing TeX packages? On a recent run, I ran into the below issue where apparently apacite.sty was missing. I did put `extra_packages: "True"`, but I'm guessing this refers to a different category of package.

```
[ERROR]   htlatex: Compilation errors in the htlatex run
[ERROR]   htlatex: Filename	Line	Message
[ERROR]   htlatex: ?	?	 LaTeX Error: File `apacite.sty' not found.
[ERROR]   htlatex: ?	8	 Emergency stop.
[FATAL]   make4ht-lib: Fatal error. Command htlatex returned exit code 1
```

**Comment by michal-h21** [comment]
The `extra-packages` expects additional Debian packages. I think that `apacite.sty` is contained in [texlive-bibtex-extra](https://packages.debian.org/sid/texlive-bibtex-extra).

**Comment by lrkrol** [comment]
Thanks for your swift response. Would this then be the correct adjustment to the YAML file? It's based on your Overleaf example.

```yaml
name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v1 
   - name: Run make4ht 
     uses: docker://ghcr.io/michal-h21/make4ht-action:latest 
     env: 
       extra_packages: "texlive-bibtex-extra"
       command: "make4ht -u -d out main.tex" 
   - name: Publish the web pages 
     uses:  peaceiris/actions-gh-pages@v3 
     with: 
       github_token: ${{ secrets.GITHUB_TOKEN }} 
       publish_dir: ./out
```

This results in the following output:

```
Package texlive-bibtex-extra is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'texlive-bibtex-extra' has no installation candidate
```
