### ISSUE TITLE
404 when installing extra packages

### ISSUE THREAD

**Issue by SzymonNastaly** [michal-h21/make4ht-action#6]
Thanks for the action! Unfortunately, I am currently getting an error during the installation of extra packages.
It is an overleaf project. 

Main `main.yml`:
```yml
name: CI 
on: [push] 
jobs: 
  build: 
   runs-on: ubuntu-latest 
   steps: 
   - uses: actions/checkout@v1 
   - name: Run make4ht 
     uses: docker://ghcr.io/michal-h21/make4ht-action:latest 
     env:
       extra_packages: "texlive-bibtex-extra"
       command: "make4ht -u -d out thesis.tex" 
   - name: Publish the web pages 
     uses:  peaceiris/actions-gh-pages@v3 
     with: 
       github_token: ${{ secrets.GITHUB_TOKEN }} 
       publish_dir: ./out
```

The action log:
```
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  texlive-bibtex-extra
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 79.5 MB of archives.
After this operation, 158 MB of additional disk space will be used.
Err:1 http://deb.debian.org/debian unstable/main amd64 texlive-bibtex-extra all 2023.20231007-2
  404  Not Found [IP: 146.75.30.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/t/texlive-extra/texlive-bibtex-extra_2023.20231007-2_all.deb  404  Not Found [IP: 146.75.30.132 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
make4ht -u -d out thesis.tex
[STATUS]  make4ht: Conversion started
[STATUS]  make4ht: Input file: thesis.tex
[ERROR]   htlatex: Compilation errors in the htlatex run
[ERROR]   htlatex: Filename	Line	Message
[ERROR]   htlatex: ?	?	 LaTeX Error: File `biblatex.sty' not found.
[ERROR]   htlatex: ?	94	 Emergency stop.
```
